# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # -- Repository of the docker image
  repository: alexwhen/docker-2048
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

securityContext: {}
  ## -- The capabilities to add/drop when running containers.
  # capabilities:
  #   drop:
  #   - ALL
  ## -- Indicates that the container must run as a non-root user. If true,
  ## the Kubelet will validate the image at runtime to ensure that it does
  ## not run as UID 0 (root) and fail to start the container if it does.
  # runAsNonRoot: true

  ## -- The UID to run the entrypoint of the container process. Defaults to
  ## user specified in image metadata if unspecified.
  # runAsUser: 1000

ingress:
  enabled: false
  className: nginx
  # -- Namespace of the ingress controller to allow traffic from.
  # If ingress controller is in the same namespace than this deployment
  # it can be empty
  namespace: ""
  annotations: {}
    # kubernetes.io/tls-acme: "true"
  hosts:
    # -- Ingress Host
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Indicates whether the Container is running.
livenessProbe:
  enabled: true
  path: /

## -- Indicates whether the Container is ready
readinessProbe:
  enabled: true
  path: /

resources:
  limits:
    # -- CPU limit for NGINX
    cpu: 100m
    # -- Memory limit for NGINX
    memory: 128Mi
  requests:
    # -- CPU request for NGINX
    cpu: 100m
    # -- Memory request for NGINX
    memory: 128Mi

autoscaling:
  # -- Minimum of relicas by the hpa
  minReplicas: 1
  # -- Maximum of replicas by the hpa
  maxReplicas: 5
  # -- Goal percentage of CPU use
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/
# -- Node Selector used to match pod to a node targetting a label
nodeSelector:
  []
  # kubernetes.io/hostname: padok-library-control-plane

# https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
# -- Affinity to match or unmatch pods to nodes and pods to pods using a particular label
affinity: {}
#  podAntiAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#    - labelSelector:
#        matchExpressions:
#        - key: app.kubernetes.io/name
#          operator: In
#          values:
#          - static
#      topologyKey: kubernetes.io/hostname

nodeAffinityPreset:
  # -- Allowed values: soft or hard
  # type: "soft"
  # -- key is the label key that the selector applies to
  # key: kubernetes.io/hostname
  # -- values is an array of string values
  # values: ["padok-library-control-plane"]
  
# -- Pod anti-affinity preset. Ignored if affinity is set.
podAntiAffinityPreset:
  # -- Allowed values: soft or hard
  # type: "soft"
  # -- topologyKey is the key for the node label that the system uses to denote the domain
  # topologyKey: kubernetes.io/hostname

# -- Pod affinity preset. Ignored if affinity is set.
podAffinityPreset:
  # -- Allowed values: soft or hard
  # type: "soft"
  # -- topologyKey is the key for the node label that the system uses to denote the domain
  # topologyKey: kubernetes.io/hostname

# https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
# -- Tolerations to match pods to nodes with a particular taint
tolerations:
  []
  ##
  # - key: node-role.kubernetes.io/master
  #   operator: "Exists"
  #   effect: "NoSchedule"

# https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
# -- Used to control how Pods are spread across your cluster among failure-domains
# such as regions, zones, nodes, and other user-defined topology domains
topologySpreadConstraints:
  []
  ##
  # - maxSkew: 1
  #   topologyKey: kubernetes.io/hostname
  #   whenUnsatisfiable: DoNotSchedule
  #   labelSelector:
  #     matchLabels:
  #       app.kubernetes.io/name: static
